package com.smartschool.api.entity;

public enum Role {
    ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_PRINCIPAL, ROLE_STATE_ADMIN, ROLE_DISTRICT_ADMIN, ROLE_TEACHER, ROLE_STUDENT, ROLE_DEPARTMENT, ROLE_DRIVER
}